### ISSUE TITLE
look into java webstart and why it fails security 

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/unison#26]
When you try the java webstart link at http://unison.sleonard.co.uk/downloads/jnlp/launch.jnlp

it says its blocked by java security
http://java.com/en/download/help/jcp_security.xml

can you look into what needs to be done to fix this?

**Comment by leonarduk** [comment]
code is at https://github.com/leonarduk/unison/tree/master/deploy

**Comment by Lithium95** [comment]
The .jnlp files only works with Java8 ..

**Comment by Lithium95** [comment]
Updating to Java8 will fix this error.. Older versions will detect it as security risks.

**Comment by leonarduk** [comment]
Doesn't seem to work, think we need to sign the jar 

http://java.com/en/download/help/jcp_security.xml or change what the applet wants to do

**Comment by leonarduk** [comment]
Maybe you can take a look at this?

**Comment by eltonnuness** [comment]
Yes, I can do this

**Comment by eltonnuness** [comment]
This is exception what occurs when you try run the JNPL:

com.sun.deploy.net.FailedDownloadException

?

**Comment by eltonnuness** [comment]
Steve,

I trying run the program, I saw the exception occurs : 

java.util.zip.ZipException: duplicate entry: org/apache/commons/net/nntp/NNTPReply.class.

Which version of unison application the Java Web Start is used to running?

**Comment by leonarduk** [comment]
The jnlp is using the jar in deploy so you will need to update the jar in that folder.

We probably want to update the Pom to copy the jar into that folder automatically

**Comment by leonarduk** [comment]
When I download I get a security exception

**Comment by eltonnuness** [comment]
Yes the same error here

**Comment by eltonnuness** [comment]
I will try more

**Comment by leonarduk** [comment]
http://docs.oracle.com/javase/tutorial/deployment/webstart/deploying.html

**Comment by leonarduk** [comment]
Now fails as its self-signed
 
this might give a free one https://www.globalsign.com/en/ssl/ssl-open-source/

**Comment by leonarduk** [comment]
have added details how to accept this and will create issue to sign it
