### ISSUE TITLE
import unison master to eclipse and see if you can run it.  update wiki where needed

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/unison#28]

**Comment by leonarduk** [comment]
Hi Lomar, how is this going? Can you now run it then?

**Comment by Lithium95** [comment]
I can run it... But I can't find any working Newsgroup.. Keep getting this error "Check your settings are correct: server news-archive.icm.edu.pl username null password null
No groups found for string : *football* on news-archive.icm.edu.pl.
Perhaps another host?"

**Comment by Lithium95** [comment]
I don't if I'm doing something wrong

**Comment by leonarduk** [comment]
Need to add wildcard characters

*football* works on news.mixmin.net

**Comment by leonarduk** [comment]
**football**

**Comment by leonarduk** [comment]
trying to add asterisk, but this just makes it bold *football

**Comment by leonarduk** [comment]
have updated https://github.com/leonarduk/unison/wiki/Download-Message-Panel

**Comment by Lithium95** [comment]
Gonna work on this

**Comment by leonarduk** [comment]
So if you have this working now you have resolved the issues you had we should close this
