### ISSUE TITLE
create developer quick start wiki page

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/unison#29]
covering tools you need : eclipse
how to import the code
how to compile the code
how to create a pull request

add screenshots to the images folder

you will need to learn this yourself to do this. ask Elton if needed and I am not around

**Comment by leonarduk** [comment]
This what you need to concentrate on now

**Comment by Lithium95** [comment]
Got it

**Comment by leonarduk** [comment]
Hi Lomar why did you not put the pictures you uploaded win.jpg etc in the page on port 119 issues?

Can you not just add them rather than deleting now?

**Comment by leonarduk** [comment]
Please use the images on the 119 page
