### ISSUE TITLE
create wiki page : known issues

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/unison#31]
Add section

No internet message
And add details of how to open port 119 once you know how

**Comment by leonarduk** [comment]
Hi Lomar, I see you have started on this, thanks.

There seems to be two pages one with known issues misspelt. Can you remove this one? Also do you have enough information to complete the child pages ? Also can you add known issues to the menu?

Thanks

**Comment by Lithium95** [comment]
Okay got it, as for the child I think I have enough information of the No internet connection... But opening port 119 still didn't work

**Comment by Lithium95** [comment]
You are right!. port 119 needs to be open... But it will require some port forwarding it seems

**Comment by leonarduk** [comment]
Can you update those wiki pages with what you have to do?

**Comment by Lithium95** [comment]
Sure as soon as I figure out how.. I'll add it..

**Comment by leonarduk** [comment]
Hi, can you complete the https://github.com/leonarduk/unison/wiki/No-Internet-Connection page? Also can you update the menu to add the two known issues pages below the link to known issues

**Comment by Lithium95** [comment]
Alright sure

**Comment by leonarduk** [comment]
So how is it going?  This has slowed down a bit.  Is there something I can do?

**Comment by Lithium95** [comment]
Added both issues

**Comment by leonarduk** [comment]
The 119 page looks good
