### ISSUE TITLE
Search alternative to locate country by ip address

### ISSUE THREAD

**Issue by eltonnuness** [leonarduk/unison#40]
The resource "http://api.hostip.info/rough.php?ip=" used on class HibernateHelper in method CreateLocation not working, search the new resource

**Comment by leonarduk** [comment]
https://freegeoip.net/

http://freegeoip.net/xml/4.2.2.2
http://freegeoip.net/json/4.2.2.2
http://freegeoip.net/csv/4.2.2.2

**Comment by leonarduk** [comment]
http://www.mkyong.com/java/json-simple-example-read-and-write-json/
