### ISSUE TITLE
Fix issues from codacy

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/unison#59]
https://www.codacy.com/app/github_65/unison/issues?bid=3302466

**Comment by eltonnuness** [comment]
Thanks for assign to me!

**Comment by eltonnuness** [comment]
Steve, you can verify if the issues what I resolved are sufficient?

**Comment by leonarduk** [comment]
There are still some issues https://www.codacy.com/app/github_65/unison/dashboard

Can you look at them?

**Comment by eltonnuness** [comment]
Ok, I will look

**Comment by eltonnuness** [comment]
Occurs (Avoid unnecessary if..then..else statements when returning booleans) in methods generated by eclipse, change this methods ?

**Comment by leonarduk** [comment]
I've fixed all but the ones for large files
