### ISSUE TITLE
update to unit tests to junit4

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/unison#6]
Currently some tests are JUnit 3 and extend import junit.framework.TestCase, we want them all to be annotation based JUnit 4

**Comment by leonarduk** [comment]
Can you do this one before any more new tests? Find any that extend TestCase and change to Junit 4.

**Comment by eltonnuness** [comment]
Ok Steve, I will change all to JUnit4

**Comment by leonarduk** [comment]
Can you complete this before adding any new ones?
