### ISSUE TITLE
Replace calls to HttpDateObject with a third party one

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/unison#82]
This looks Iike it was copied from another library. We should look to remove it and use the third party version if its a well tested one.

**Comment by eltonnuness** [comment]
Hey Steve

I found it, the class, apparently:
https://www.gnu.org/software/classpathx/inetlib/javadoc/gnu/inet/http/HTTPDateFormat.html

In the website of gnu.org, I locate the download project.
https://www.gnu.org/software/classpath/downloads/downloads.html

Inside the folders : /classpath-0.99/gnu/java/net/protocol/http/HTTPDateFormat.java, the class looks like the same.

But, I did no found in maven repository, How I need proceed?

**Comment by eltonnuness** [comment]
Or I need replace the calls of this class, for another class what make the same things ?

**Comment by eltonnuness** [comment]
I saw the uses of the parser and the HttpDateObject is used to parse String to Date, I think I can find another class in other library that perform the same thing, what you think?

**Comment by eltonnuness** [comment]
Yes, maybe the LocalDateTime can help us

**Comment by eltonnuness** [comment]
Hey Steve,

I learned how use the DateTime of Java8, I can create a method in StringUtils to make the convertion of String to Date with LocalDate and ZonedDateTime ?, or you want that I no create additional methods?, I think is better create a method in any helper class because of validations of empty or null String value and others.

Thanks!

**Comment by eltonnuness** [comment]
I will create a new method in StringUtils to convert the String to Date with LocalDate and ZonedDateTime ok?

**Comment by leonarduk** [comment]
Ok
